# fly.toml app configuration file generated for beth-stack-site on 2023-09-04T12:45:33+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "beth-stack-site"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
  [[http_service.checks]]
    grace_period = "2s"
    interval = "10s"
    method = "GET"
    timeout = "5s"
    path = "/"

[deploy]
  strategy = "canary"