name: Test and Deploy
on:
  push:
    branches:
      - master
jobs:
  test-and-deploy:
    name: Test and Deploy
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_HOST: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - name: Setup database
        run: psql -h localhost -U postgres -c 'CREATE DATABASE "test";'
        env:
          PGPASSWORD: postgres
      - run: bun test
        env:
          NODE_ENV: "test"
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/test
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}